modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/Guiirs/SECURITY-CRAFT/issues"

[[mods]]
modId="scccompat"
version="${file.jarVersion}"
displayName="SecurityCraft CC:Tweaked Compatibility"
updateJSONURL="https://github.com/Guiirs/SECURITY-CRAFT/releases"
displayURL="https://github.com/Guiirs/SECURITY-CRAFT"
logoFile="logo.png"
credits="Guiirs - Integration between SecurityCraft and CC:Tweaked"
authors="Guiirs"
description='''
Adds compatibility between SecurityCraft and CC:Tweaked, allowing Security Cameras 
to be used as ComputerCraft peripherals. Connect cameras directly to computers 
and access their feeds programmatically!
'''

[[dependencies.scccompat]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.scccompat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.scccompat]]
    modId="securitycraft"
    mandatory=true
    versionRange="[1.9.7,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.scccompat]]
    modId="computercraft"
    mandatory=true
    versionRange="[1.101.0,)"
    ordering="NONE"
    side="BOTH"
